# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  #welcome: circleci/welcome-orb@0.4.1
  katalon-studio: katalon/katalon-studio@23.0.11
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments:  katalonc -noSplash -runMode=console -projectPath="demo.prj" -retry=1 -retryStrategy=allExecutions -testSuitePath="Test Suites/Verify Operations" -executionProfile="default" -browserType="Chrome (headless)" -apiKey="2d27c4cf-f3d9-447b-8df0-17888a29e2f9" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true
