<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Audio__multi-card-creative-desktop_Imag_143b30</name>
   <tag></tag>
   <elementGuidId>fc11a517-c426-4a07-bd4b-bd6bb1bde661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-section.a-spacing-none._multi-card-creative-desktop_ImageContainer_container__1DI1V._multi-card-creative-desktop_Layout_block__1vI8-._multi-card-creative-desktop_Layout_hFull__2lnNw._multi-card-creative-desktop_Layout_wFull__3f8b2._multi-card-creative-desktop_Layout_row__3CEm0._multi-card-creative-desktop_Layout_itemsCenter__3flfN._multi-card-creative-desktop_Layout_contentCenter__3BjNx > img._multi-card-creative-desktop_Image_image__1pfbQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceiZk_BUHDXj6lguPkMZlYug']/div/div[2]/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Yamaha Soundbar with Built-in Dual subwoofer, DTS Virtual:X and Bluetooth Streaming - SRB20AB (Black)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61FgPPsUZxL._AC_SX180_SY120_QL70_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61FgPPsUZxL._AC_SX180_SY120_QL70_.jpg 1x,https://m.media-amazon.com/images/I/61FgPPsUZxL._AC_SX360_SY240_QL70_.jpg 2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_multi-card-creative-desktop_Image_image__1pfbQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceiZk_BUHDXj6lguPkMZlYug&quot;)/div[@class=&quot;_multi-card-creative-desktop_DesktopContainer_content__2rsXy&quot;]/div[@class=&quot;a-section a-spacing-none _multi-card-creative-desktop_Layout_block__1vI8- _multi-card-creative-desktop_Layout_row__3CEm0&quot;]/div[@class=&quot;_multi-card-creative-desktop_DesktopGridColumn_gridColumn__2Jfab&quot;]/div[@class=&quot;a-section a-spacing-none _multi-card-creative-desktop_ItemContainer_container__3q4Jr _multi-card-creative-desktop_Layout_block__1vI8- _multi-card-creative-desktop_Layout_hFull__2lnNw _multi-card-creative-desktop_Layout_wFull__3f8b2 _multi-card-creative-desktop_Layout_col__358pf&quot;]/div[@class=&quot;a-section a-spacing-micro _multi-card-creative-desktop_style_productImage__1CRqz&quot;]/a[@class=&quot;a-spacing-none a-link-normal _multi-card-creative-desktop_Link_link__gJc5l _multi-card-creative-desktop_Link_fullSize__1_hF0 _multi-card-creative-desktop_Link_hidden__L-XDK&quot;]/div[@class=&quot;a-section a-spacing-none _multi-card-creative-desktop_ImageContainer_container__1DI1V _multi-card-creative-desktop_Layout_block__1vI8- _multi-card-creative-desktop_Layout_hFull__2lnNw _multi-card-creative-desktop_Layout_wFull__3f8b2 _multi-card-creative-desktop_Layout_row__3CEm0 _multi-card-creative-desktop_Layout_itemsCenter__3flfN _multi-card-creative-desktop_Layout_contentCenter__3BjNx&quot;]/img[@class=&quot;_multi-card-creative-desktop_Image_image__1pfbQ&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceiZk_BUHDXj6lguPkMZlYug']/div/div[2]/div/div/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Yamaha Soundbar with Built-in Dual subwoofer, DTS Virtual:X and Bluetooth Streaming - SRB20AB (Black)']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
